### ISSUE TITLE
How do I compile it

### ISSUE THREAD

**Issue by czadikem** [Bonono63/Create---Fabric-Edition#1]
Hello I love the project but how do I compile a 1.16.5 jar using your code?

**Comment by Bonono63** [comment]
I use intellij idea community to code the mod itself, but currently the project is compiling correctly, so once I fix it you'll be able to compile it correctly. if you haven't compiled a mod before I recommend a different project and using the instruction provided by [https://fabricmc.net/wiki/tutorial:setup](url)

**Comment by czadikem** [comment]
So there is no way for me to try this then?  As of this time?

**Comment by Bonono63** [comment]
The code doesn't work because it is taken directly from the Create GitHub and needs to be adapted to fabric. So no you can not compile it. There was a import problem before even that, but in the resent commit I fixed it and brought in the create code so you can import it into Intellij, but not compile the mod.

**Comment by czadikem** [comment]
Got it. Thank you for your time and this great project.

**Comment by Bonono63** [comment]
no problem
